#file to test

import collections
EPSILON = 'ε'
class Automata:
     def __init__(self, exp):
        self.id = exp 
        self.states = []

class State: 
   def __init__(self,num):
     self.id = num
     self.transitions = []
     self.accept = False 

class Transition: 
  def __init__(self,sym,to):
        self.symbol = sym
        self.to = to

def is_in_language(automata, expresion):
  if expresion == ' ' or expresion == '':
      expresion = EPSILON
  actual = [0]
  actual = cerradura(automata, actual)
  i = 0
  while True:
      temp = []
      for num in actual:
          for transition in automata.states[num].transitions:
              if transition.symbol == expresion[i] and transition.to not in temp:
                  temp.append(transition.to)
      i += 1
      temp = cerradura(automata, temp)
      if not temp and expresion == EPSILON:
          break
      actual = temp.copy()
      if i > len(expresion)-1:
          break
  for id in actual:
      if automata.states[id].accept:
          return True
  return False

def cerradura(automata, actual):
  for num in actual:
      for transition in automata.states[num].transitions:
          if transition.symbol == EPSILON and transition.to not in actual:
              actual.append(transition.to)
  return actual

def read_word(file, actual):
  temp_word = ''
  while actual < len(file):
      if(file[actual] == ' ' or file[actual] == '\n') and (len(temp_word)>0):
          break
      elif file[actual] == ' ' or file[actual] == '\n':
          actual += 1
      else:
          temp_word += file[actual]
          actual += 1
  return temp_word, actual

def word_break(file, automata0, actual = 0):
  temp = ''
  validos = []
  while actual < len(file):
      temp += file[actual]
      if is_in_language(automata0, temp):
          validos.append(temp)
      actual += 1
  if validos:
      return max(validos, key = len)
  return False
def main():
  automatas = []
  automata0 = Automata("completo")
  temp_node= State(0)
  temp_transition = Transition('A', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('B', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('C', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('D', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('E', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('F', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('G', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('H', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('I', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('J', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('K', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('L', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('M', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('N', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Ñ', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('O', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('P', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Q', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('R', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('S', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('T', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('U', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('V', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('W', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('X', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Y', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Z', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('a', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('b', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('c', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('d', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('e', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('f', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('g', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('h', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('i', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('j', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('k', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('l', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('m', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('n', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('ñ', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('o', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('p', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('q', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('r', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('s', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('t', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('u', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('v', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('w', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('x', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('y', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('z', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('0', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('"', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x00', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x01', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x02', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x03', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x04', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x05', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x06', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x07', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x08', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0b', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0c', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0e', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0f', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x10', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x11', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x12', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x13', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x14', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x15', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x16', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x17', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x18', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x19', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1a', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1b', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1c', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1d', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1e', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1f', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('!', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('#', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('$', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('%', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('&', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition("'", 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('*', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(',', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('/', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(':', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(';', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('?', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('@', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(']', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('^', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('_', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('`', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('~', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x7f', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x80', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Ꮸ', 4)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\t', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\n', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\r', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Ꮚ', 3)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Ꮙ', 3)
  temp_node.transitions.append(temp_transition)
  automata0.states.append(temp_node)
  temp_node= State(1)
  temp_node.accept = True
  temp_transition = Transition('Ꮣ', 3)
  temp_node.transitions.append(temp_transition)
  automata0.states.append(temp_node)
  temp_node= State(2)
  temp_transition = Transition('Ꮣ', 3)
  temp_node.transitions.append(temp_transition)
  automata0.states.append(temp_node)
  temp_node= State(3)
  temp_node.accept = True
  automata0.states.append(temp_node)
  temp_node= State(4)
  temp_transition = Transition('0', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 5)
  temp_node.transitions.append(temp_transition)
  automata0.states.append(temp_node)
  temp_node= State(5)
  temp_transition = Transition('0', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 5)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(')', 6)
  temp_node.transitions.append(temp_transition)
  automata0.states.append(temp_node)
  temp_node= State(6)
  temp_node.accept = True
  temp_transition = Transition('.', 7)
  temp_node.transitions.append(temp_transition)
  automata0.states.append(temp_node)
  temp_node= State(7)
  temp_transition = Transition('.', 8)
  temp_node.transitions.append(temp_transition)
  automata0.states.append(temp_node)
  temp_node= State(8)
  temp_transition = Transition('Ꮸ', 9)
  temp_node.transitions.append(temp_transition)
  automata0.states.append(temp_node)
  temp_node= State(9)
  temp_transition = Transition('0', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 10)
  temp_node.transitions.append(temp_transition)
  automata0.states.append(temp_node)
  temp_node= State(10)
  temp_transition = Transition('0', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 10)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(')', 3)
  temp_node.transitions.append(temp_transition)
  automata0.states.append(temp_node)
  automatas.append(automata0)

  automata1 = Automata("ident")
  temp_node= State(0)
  temp_transition = Transition('A', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('B', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('C', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('D', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('E', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('F', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('G', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('H', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('I', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('J', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('K', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('L', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('M', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('N', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Ñ', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('O', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('P', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Q', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('R', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('S', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('T', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('U', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('V', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('W', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('X', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Y', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Z', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('a', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('b', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('c', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('d', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('e', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('f', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('g', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('h', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('i', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('j', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('k', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('l', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('m', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('n', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('ñ', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('o', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('p', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('q', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('r', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('s', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('t', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('u', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('v', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('w', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('x', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('y', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('z', 1)
  temp_node.transitions.append(temp_transition)
  automata1.states.append(temp_node)
  temp_node= State(1)
  temp_node.accept = True
  temp_transition = Transition('A', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('B', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('C', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('D', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('E', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('F', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('G', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('H', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('I', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('J', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('K', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('L', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('M', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('N', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Ñ', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('O', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('P', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Q', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('R', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('S', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('T', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('U', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('V', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('W', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('X', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Y', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Z', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('a', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('b', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('c', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('d', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('e', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('f', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('g', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('h', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('i', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('j', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('k', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('l', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('m', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('n', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('ñ', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('o', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('p', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('q', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('r', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('s', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('t', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('u', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('v', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('w', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('x', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('y', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('z', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('0', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 1)
  temp_node.transitions.append(temp_transition)
  automata1.states.append(temp_node)
  automatas.append(automata1)

  automata2 = Automata("string")
  temp_node= State(0)
  temp_transition = Transition('"', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x00', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x01', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x02', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x03', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x04', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x05', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x06', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x07', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x08', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0b', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0c', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0e', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0f', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x10', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x11', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x12', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x13', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x14', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x15', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x16', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x17', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x18', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x19', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1a', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1b', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1c', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1d', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1e', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1f', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('!', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('#', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('$', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('%', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('&', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition("'", 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('(', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(')', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('*', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('+', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(',', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('-', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('.', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('/', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('0', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(':', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(';', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('<', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('=', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('>', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('?', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('@', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('A', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('B', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('C', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('D', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('E', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('F', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('G', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('H', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('I', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('J', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('K', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('L', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('M', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('N', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('O', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('P', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Q', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('R', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('S', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('T', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('U', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('V', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('W', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('X', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Y', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Z', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('[', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\\', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(']', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('^', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('_', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('`', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('a', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('b', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('c', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('d', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('e', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('f', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('g', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('h', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('i', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('j', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('k', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('l', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('m', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('n', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('o', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('p', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('q', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('r', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('s', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('t', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('u', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('v', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('w', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('x', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('y', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('z', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('{', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('|', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('}', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('~', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x7f', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x80', 0)
  temp_node.transitions.append(temp_transition)
  automata2.states.append(temp_node)
  temp_node= State(1)
  temp_node.accept = True
  temp_transition = Transition('"', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x00', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x01', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x02', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x03', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x04', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x05', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x06', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x07', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x08', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0b', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0c', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0e', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0f', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x10', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x11', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x12', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x13', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x14', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x15', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x16', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x17', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x18', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x19', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1a', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1b', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1c', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1d', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1e', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1f', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('!', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('#', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('$', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('%', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('&', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition("'", 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('(', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(')', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('*', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('+', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(',', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('-', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('.', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('/', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('0', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(':', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(';', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('<', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('=', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('>', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('?', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('@', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('A', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('B', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('C', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('D', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('E', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('F', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('G', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('H', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('I', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('J', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('K', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('L', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('M', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('N', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('O', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('P', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Q', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('R', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('S', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('T', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('U', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('V', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('W', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('X', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Y', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Z', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('[', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\\', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(']', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('^', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('_', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('`', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('a', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('b', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('c', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('d', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('e', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('f', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('g', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('h', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('i', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('j', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('k', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('l', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('m', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('n', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('o', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('p', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('q', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('r', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('s', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('t', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('u', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('v', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('w', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('x', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('y', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('z', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('{', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('|', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('}', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('~', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x7f', 0)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x80', 0)
  temp_node.transitions.append(temp_transition)
  automata2.states.append(temp_node)
  automatas.append(automata2)

  automata3 = Automata("char")
  temp_node= State(0)
  temp_transition = Transition('A', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('B', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('C', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('D', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('E', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('F', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('G', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('H', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('I', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('J', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('K', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('L', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('M', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('N', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Ñ', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('O', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('P', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Q', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('R', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('S', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('T', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('U', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('V', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('W', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('X', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Y', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Z', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('a', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('b', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('c', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('d', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('e', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('f', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('g', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('h', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('i', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('j', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('k', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('l', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('m', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('n', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('ñ', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('o', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('p', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('q', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('r', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('s', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('t', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('u', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('v', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('w', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('x', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('y', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('z', 1)
  temp_node.transitions.append(temp_transition)
  automata3.states.append(temp_node)
  temp_node= State(1)
  temp_transition = Transition('Ꮣ', 2)
  temp_node.transitions.append(temp_transition)
  automata3.states.append(temp_node)
  temp_node= State(2)
  temp_node.accept = True
  automata3.states.append(temp_node)
  automatas.append(automata3)

  automata4 = Automata("charnumber")
  temp_node= State(0)
  temp_transition = Transition('Ꮸ', 1)
  temp_node.transitions.append(temp_transition)
  automata4.states.append(temp_node)
  temp_node= State(1)
  temp_transition = Transition('0', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 2)
  temp_node.transitions.append(temp_transition)
  automata4.states.append(temp_node)
  temp_node= State(2)
  temp_transition = Transition('0', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(')', 3)
  temp_node.transitions.append(temp_transition)
  automata4.states.append(temp_node)
  temp_node= State(3)
  temp_node.accept = True
  automata4.states.append(temp_node)
  automatas.append(automata4)

  automata5 = Automata("charinterval")
  temp_node= State(0)
  temp_transition = Transition('Ꮸ', 1)
  temp_node.transitions.append(temp_transition)
  automata5.states.append(temp_node)
  temp_node= State(1)
  temp_transition = Transition('0', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 2)
  temp_node.transitions.append(temp_transition)
  automata5.states.append(temp_node)
  temp_node= State(2)
  temp_transition = Transition('0', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 2)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(')', 3)
  temp_node.transitions.append(temp_transition)
  automata5.states.append(temp_node)
  temp_node= State(3)
  temp_transition = Transition('.', 4)
  temp_node.transitions.append(temp_transition)
  automata5.states.append(temp_node)
  temp_node= State(4)
  temp_transition = Transition('.', 5)
  temp_node.transitions.append(temp_transition)
  automata5.states.append(temp_node)
  temp_node= State(5)
  temp_transition = Transition('Ꮸ', 6)
  temp_node.transitions.append(temp_transition)
  automata5.states.append(temp_node)
  temp_node= State(6)
  temp_transition = Transition('0', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 7)
  temp_node.transitions.append(temp_transition)
  automata5.states.append(temp_node)
  temp_node= State(7)
  temp_transition = Transition('0', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 7)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(')', 8)
  temp_node.transitions.append(temp_transition)
  automata5.states.append(temp_node)
  temp_node= State(8)
  temp_node.accept = True
  automata5.states.append(temp_node)
  automatas.append(automata5)

  automata6 = Automata("nontoken")
  temp_node= State(0)
  temp_transition = Transition('\x00', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x01', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x02', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x03', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x04', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x05', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x06', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x07', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x08', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\t', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\n', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0b', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0c', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\r', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0e', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x0f', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x10', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x11', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x12', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x13', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x14', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x15', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x16', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x17', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x18', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x19', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1a', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1b', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1c', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1d', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1e', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x1f', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition("'", 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('!', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('"', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('#', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('$', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('%', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('&', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('*', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(',', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('/', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('0', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('1', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('2', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('3', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('4', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('5', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('6', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('7', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('8', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('9', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(':', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(';', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('?', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('@', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('A', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('B', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('C', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('D', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('E', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('F', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('G', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('H', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('I', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('J', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('K', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('L', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('M', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('N', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('O', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('P', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Q', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('R', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('S', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('T', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('U', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('V', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('W', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('X', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Y', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('Z', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition(']', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('^', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('_', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('`', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('a', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('b', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('c', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('d', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('e', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('f', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('g', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('h', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('i', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('j', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('k', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('l', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('m', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('n', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('o', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('p', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('q', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('r', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('s', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('t', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('u', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('v', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('w', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('x', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('y', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('z', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('~', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x7f', 1)
  temp_node.transitions.append(temp_transition)
  temp_transition = Transition('\x80', 1)
  temp_node.transitions.append(temp_transition)
  automata6.states.append(temp_node)
  temp_node= State(1)
  temp_node.accept = True
  automata6.states.append(temp_node)
  automatas.append(automata6)

  automata7 = Automata("startcode")
  temp_node= State(0)
  temp_transition = Transition('Ꮚ', 1)
  temp_node.transitions.append(temp_transition)
  automata7.states.append(temp_node)
  temp_node= State(1)
  temp_node.accept = True
  automata7.states.append(temp_node)
  automatas.append(automata7)

  automata8 = Automata("endcode")
  temp_node= State(0)
  temp_transition = Transition('Ꮙ', 1)
  temp_node.transitions.append(temp_transition)
  automata8.states.append(temp_node)
  temp_node= State(1)
  temp_node.accept = True
  automata8.states.append(temp_node)
  automatas.append(automata8)

  print('archivo a revisar?')
  archivo = input()
  prueba = open('../test/'+archivo)
  data = prueba.read()
  prueba.close()
  i = 0
  last = 0
  data = data.replace('CHR(', 'Ꮸ')
  data = data.replace('(.', 'Ꮚ')
  data = data.replace('.)', 'Ꮙ')
  while i < len(data):
      valid = word_break(data, automata0, i)
      if valid:
          if last != 0 and (i - last > 0):
              while last < i:
                  print(data[last], end='')
                  last += 1
              print(': False')
          last += len(valid)
          aut = 1
          while aut<len(automatas):
              if (is_in_language(automatas[aut], valid)):
                  if 'Ꮸ' in valid:
                    valid = valid.replace('Ꮸ', 'CHR(')
                  elif 'Ꮚ' in valid:
                    valid = valid.replace('Ꮚ', '(.')
                  elif 'Ꮙ' in valid:
                    valid = valid.replace('Ꮙ', '.)')
                  print(valid, ': ', automatas[aut].id)
                  break
              aut += 1
          i += len(valid)
      else:
          i+=1
if __name__ == "__main__":
   main()